# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'bin/*'
    - '*.gemspec'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
